In [13]:
#Loading Manhattan EZ pass data set

import pandas as pd
#import polyline

manhattanEZPass = pd.read_csv("sample_data/NYC OpenData EZ Pass Reader.csv")


print(manhattanEZPass.info(),'\n')
print(manhattanEZPass.shape)
manhattanEZPass.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   sid                           351 non-null    int64
 1   link_name                     351 non-null    object
 2   borough                       351 non-null    object
 3   polyline                      351 non-null    object
 4   link_length_ft                351 non-null    float64
 5   aggregation_period_sec        351 non-null    int64
 6   n_samples                     351 non-null    int64
 7   median_calculation_timestamp  351 non-null    object
 8   median_tt_sec                 351 non-null    float64
 9   median_speed_fps              351 non-null    float64
dtypes: float64(3), int64(3), object(4)
memory usage: 27.6+ KB
None

(351, 10)

,sid,link_name,borough,polyline,link_length_ft,aggregation_period_sec,n_samples,median_calculation_timestamp,median_tt_sec,median_speed_fps
0,1004,42nd Street - Eastbound - Lexington Ave to 3rd...,Manhattan,agvwFxmobMfCeI,514.26,900,28,3/16/2026 16:15:01,69.5,7.40
1,1011,42nd Street - Westbound - Lexington Ave to Mad...,Manhattan,_hvwF|lobMmGhS,1024.34,900,9,3/16/2026 16:15:01,723.0,1.42
2,2001,Lexington Avenue - Southbound - 49th St to 42n...,Manhattan,ecwwFdynbMlZhS,1836.18,900,55,3/16/2026 16:15:01,152.0,12.08
3,3002,Lexington Avenue - Southbound - 57th St to 49t...,Manhattan,ybxwF`bnbM??vRxMzJfG,2109.11,900,36,3/16/2026 16:15:01,125.0,16.87
4,3006,57th Street - Eastbound - Lexington Ave to 3rd...,Manhattan,kbxwFlbnbMfAiD`AuC,508.77,900,24,3/16/2026 16:15:01,18.0,28.26

In [17]:
#Loading NYC Real-Time Traffic Speed Data

nycTrafficData = pd.read_csv("sample_data/NYC Real-Time Traffic Speed Data.csv")

nycTrafficData.head()

,sid,link_name,borough,polyline,link_length_ft,aggregation_period_sec,n_samples,median_calculation_timestamp,median_tt_sec,median_speed_fps
0,2012,49th Street - Westbound - Lexington Ave to Mad...,Manhattan,ecwwFdynbMgC~HgC~H,1013.97,900,14,3/15/2026 12:40:12,616.5,1.64
1,3002,Lexington Avenue - Southbound - 57th St to 49t...,Manhattan,ybxwF`bnbM??vRxMzJfG,2109.11,900,20,3/15/2026 12:40:12,139.0,15.17
2,5006,3rd Avenue - Northbound - 49th St to 57th St,Manhattan,a_wwFfonbMq^aV,2105.67,900,20,3/15/2026 12:40:12,73.5,28.65
3,6003,57th Street - Westbound - 3rd Ave to Lexington...,Manhattan,a_xwFxwmbMeC|H,502.77,900,39,3/15/2026 12:40:12,21.0,23.94
4,8118,34th Street - Westbound - Madison Ave to 5th Ave,Manhattan,{puwFdxpbMeC|H,502.84,900,28,3/15/2026 12:40:12,24.5,20.52